// *** LIST BIKE STATION ***
export const LIST_BIKE_STATION_REQUEST = 'LIST_BIKE_STATION_REQUEST';
export const LIST_BIKE_STATION_SUCCESS = 'LIST_BIKE_STATION_SUCCESS';
export const LIST_BIKE_STATION_FAIL = 'LIST_BIKE_STATION_FAIL';

// *** ADD BIKE STATION ***
export const ADD_BIKE_STATION_REQUEST = 'ADD_BIKE_STATION_REQUEST';
export const ADD_BIKE_STATION_SUCCESS = 'ADD_BIKE_STATION_SUCCESS';
export const ADD_BIKE_STATION_FAIL = 'ADD_BIKE_STATION_FAIL';

// *** BIKE STATION DETAILS ***
export const BIKE_STATION_DETAILS_REQUEST = 'BIKE_STATION_DETAILS_REQUEST';
export const BIKE_STATION_DETAILS_SUCCESS = 'BIKE_STATION_DETAILS_SUCCESS';
export const BIKE_STATION_DETAILS_FAIL = 'BIKE_STATION_DETAILS_FAIL';
