// List Bikes
export const LIST_BIKE_REQUEST = 'LIST_BIKE_REQUEST';
export const LIST_BIKE_SUCCESS = 'LIST_BIKE_SUCCESS';
export const LIST_BIKE_FAIL = 'LIST_BIKE_FAIL';

// Bike Details
export const GET_BIKE_DETAILS_REQUEST = 'GET_BIKE_DETAILS_REQUEST';
export const GET_BIKE_DETAILS_SUCCESS = 'GET_BIKE_DETAILS_SUCCESS';
export const GET_BIKE_DETAILS_FAIL = 'GET_BIKE_DETAILS_FAIL';

// Add Bike
export const ADD_BIKE_REQUEST = 'ADD_BIKE_REQUEST';
export const ADD_BIKE_SUCCESS = 'ADD_BIKE_SUCCESS';
export const ADD_BIKE_FAIL = 'ADD_BIKE_FAIL';

// Delete Bike
export const DELETE_BIKE_REQUEST = 'DELETE_BIKE_REQUEST';
export const DELETE_BIKE_SUCCESS = 'DELETE_BIKE_SUCCESS';
export const DELETE_BIKE_FAIL = 'DELETE_BIKE_FAIL';
