// Create Booking
export const NEW_BOOKING_REQUEST = 'NEW_BOOKING_REQUEST';
export const NEW_BOOKING_SUCCESS = 'NEW_BOOKING_SUCCESS';
export const NEW_BOOKING_FAIL = 'NEW_BOOKING_FAIL';

// List Booking
export const LIST_BOOKING_REQUEST = 'LIST_BOOKING_REQUEST';
export const LIST_BOOKING_SUCCESS = 'LIST_BOOKING_SUCCESS';
export const LIST_BOOKING_FAIL = 'LIST_BOOKING_FAIL';

// Booking Details
export const GET_BOOKING_DETAILS_REQUEST = 'GET_BOOKING_DETAILS_REQUEST';
export const GET_BOOKING_DETAILS_SUCCESS = 'GET_BOOKING_DETAILS_SUCCESS';
export const GET_BOOKING_DETAILS_FAIL = 'GET_BOOKING_DETAILS_FAIL';

// Edit Booking
export const EDIT_BOOKING_REQUEST = 'EDIT_BOOKING_REQUEST';
export const EDIT_BOOKING_SUCCESS = 'EDIT_BOOKING_SUCCESS';
export const EDIT_BOOKING_FAIL = 'EDIT_BOOKING_FAIL';

// Delete Booking
export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAIL = 'DELETE_BOOKING_FAIL';

// Start Booking
export const START_BOOKING_REQUEST = 'START_BOOKING_REQUEST';
export const START_BOOKING_SUCCESS = 'START_BOOKING_SUCCESS';
export const START_BOOKING_FAIL = 'START_BOOKING_FAIL';

// End Booking
export const END_BOOKING_REQUEST = 'END_BOOKING_REQUEST';
export const END_BOOKING_SUCCESS = 'END_BOOKING_SUCCESS';
export const END_BOOKING_FAIL = 'END_BOOKING_FAIL';
